# Generated by Django 3.2.5 on 2021-07-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=30)),
                ('country', models.CharField(choices=[('', '-------Select Country-------'), ('Bangladesh', 'Bangladesh'), ('India', 'India'), ('Pakistan', 'Pakistan'), ('NewYork', 'New York')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='buyproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.main_user')),
            ],
        ),
    ]
